export const ADD_DOGBARK = 'ADD_DOGBARK';
export const DELETE_DOGBARK = 'DELETE_DOGBARK';
export const EDIT_DOGBARK = 'EDIT_DOGBARK';
export const COMPLETE_DOGBARK = 'COMPLETE_DOGBARK';
export const COMPLETE_ALL = 'COMPLETE_ALL';
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED';
